#!/bin/bash
# A script that creates a file and make them Ruby executable

if [ $# -ne 1 ]
then
	echo "Usage: './createExec nameOfFile'"
else
	file=$1
	echo "#!/usr/bin/env ruby" > $file
	chmod +x $file
	ls -l $file
fi
