#!/usr/bin/env bash
# A script that displays To infinity and beyond indefinitely and handles SIGINT

trap "exit" SIGINT
# trap "echo "Terminated" ; exit" SIGTERM
while $1
do
	echo "To infinity and beyond"
	sleep 2
done
