#!/usr/bin/env bash
# A script that displays To infinity and beyond indefinitely and handle SIGTERM.

trap "echo 'I am invincible!!!'" SIGTERM
while $1
do
	echo "To infinity and beyond"
	sleep 2
done
